ultranet_core_homepage:
    path:     /
    defaults: { _controller: UltranetCoreBundle:Core:index }

ultranet_core_contactpage:
    path:     /contact
    defaults: { _controller: UltranetCoreBundle:Contact:index }


ultranet_core_formationspage:
    path:     /formations
    defaults: { _controller: UltranetCoreBundle:Formation:index }


ultranet_core_show_formationpage:
    path:     /formations/{slug}
    defaults: { _controller: UltranetCoreBundle:Formation:show }

ultranet_core_contact_formpage:
    path:     /contact/form
    defaults: { _controller: UltranetCoreBundle:Contact:form }
    methods: [POST]
